[build]
  command   = "npm run build"
  publish   = "client/dist"
  functions = "netlify/functions"

[[redirects]]
  from    = "/api/*"
  to      = "/.netlify/functions/api/:splat"
  status  = 200
  force   = true
