[build]
  command   = "npm install && cd client && npm ci && npm run build"
  publish   = "client/dist"
  functions = "server/functions"

[functions]
  timeout = 15

[context.production.environment]
  NODE_ENV = "production"
